### ISSUE TITLE
getAccount and getStatement isn't working

### ISSUE THREAD

**Issue by Godskid89** [hamzzy/Mono-Python#14]
i keep geting this error 

`({'message': 'This account does not exist.'}, 404)
Traceback (most recent call last):
  File "/Users/josepholadokun/Desktop/juice/sumer/mono/user_details.py", line 17, in <module>
    account = mono.getAccount()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymono/Mono.py", line 25, in getAccount
    return self._handle_request("GET", "accounts/" + self.GetUserId())
TypeError: can only concatenate str (not "NoneType") to str`

**Comment by hamzzy** [comment]
the data type you are returning is incorrect.


string is required and not a Type

**Comment by hamzzy** [comment]
probably check your   ` mono.SetUserId(data.get("id"))`

i think you didn't input the right data.
